export const ADD_CONTACTO = 'ADD_CONTACTO';
export const TOGGLE_SHOW = 'TOGGLE_SHOW';
export const EDITAR_CONTACTO = 'EDITAR_CONTACTO';
export const ACTUALIZAR_CONTACTO = 'ACTUALIZAR_CONTACTO';
export const BORRAR_CONTACTO = 'BORRAR_CONTACTO';